# Generated by Django 4.1.3 on 2022-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('hora_inscripcion', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=300)),
            ],
        ),
    ]
